const NEXT_PUBLIC_CHANNEL_NAME = "ChannelName";
const NEXT_PUBLIC_CHANNEL_TYPE = "marketing";
const NEXT_PUBLIC_CHANNEL_PLATFORM = "custom";
const NEXT_PUBLIC_CHANNEL_LISTABLE_FROM_UI = false;
const NEXT_PUBLIC_CHANNEL_PLATFORM_CLIENT_ID = "xxxxxxxxxx-123456789";
const NEXT_PUBLIC_CHANNEL_PLATFORM_AUTH_WINDOW_URL = "/fake_auth_page";

export default {
    NEXT_PUBLIC_CHANNEL_LISTABLE_FROM_UI,
    NEXT_PUBLIC_CHANNEL_NAME,
    NEXT_PUBLIC_CHANNEL_PLATFORM,
    NEXT_PUBLIC_CHANNEL_PLATFORM_AUTH_WINDOW_URL,
    NEXT_PUBLIC_CHANNEL_PLATFORM_CLIENT_ID,
    NEXT_PUBLIC_CHANNEL_TYPE,
};
